language: php

sudo: required

matrix:
  include:
    - php: 7.3
      env: SW_VERSION="develop"
    - php: 7.4
      env: SW_VERSION="develop"
    - php: master
      env: SW_VERSION="develop"

  allow_failures:
    - php: master

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash ./tests/swow.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add ./tests/ci.ini
  - php --ri swow

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer update -o

script:
  - composer analyse
  - composer test
